<?php

namespace App\Extensions\Internals;

enum BuildHooks
{
    case BEFORE_INITIAL_CLEAR_TEMP_DIRECTORY;
    case AFTER_INITIAL_CLEAR_TEMP_DIRECTORY;

    case BEFORE_CREATE_TEMP_DIRECTORY;
    case AFTER_CREATE_TEMP_DIRECTORY;

    case BEFORE_DOWNLOAD_FROM_S3;
    case AFTER_DOWNLOAD_FROM_S3;

    case BEFORE_BUILD_SATIS_REPOSITORY;
    case AFTER_BUILD_SATIS_REPOSITORY;

    case BEFORE_PREPARE_CONFIG_FOR_SATIS;
    case AFTER_PREPARE_CONFIG_FOR_SATIS;

    case BEFORE_PURGE_SATIS_REPOSITORY;
    case AFTER_PURGE_SATIS_REPOSITORY;

    case BEFORE_CLEAR_SATIS_CONFIG_FILE;
    case AFTER_CLEAR_SATIS_CONFIG_FILE;

    case BEFORE_UPLOAD_TO_S3;
    case AFTER_UPLOAD_TO_S3;

    case BEFORE_REMOVE_MISSING_FILES_FROM_S3;
    case AFTER_REMOVE_MISSING_FILES_FROM_S3;

    case BEFORE_FINAL_CLEAR_TEMP_DIRECTORY;
    case AFTER_FINAL_CLEAR_TEMP_DIRECTORY;
}
