name: Build PHAR Archive

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, develop ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*', 'v*.*', 'v*' ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-phar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-all

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Get the tag name
        if:   startsWith(github.ref, 'refs/tags/')
        run:  echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build PHAR archive
        if:   startsWith(github.ref, 'refs/tags/')
        run: php s3-satis app:build --build-version=${{ env.TAG }}

      - name: Build PHAR archive
        if:   ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: php s3-satis app:build --build-version=$(git rev-parse --short "$GITHUB_SHA")

      - name: Rename phar
        run: mv builds/s3-satis builds/s3-satis.phar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: binary
          path: builds/*
          if-no-files-found: error
          retention-days: 30

      - name: Release
        uses: softprops/action-gh-release@v1
        if:   startsWith(github.ref, 'refs/tags/')
        with:
          files: builds/s3-satis.phar
